extern const GeoLayout mario_armature_002_switch_option_002[];
extern const GeoLayout mario_right_hand_open_armature[];
extern const GeoLayout mario_left_hand_open_armature[];
extern const GeoLayout mario_left_hand_peace_armature[];
extern const GeoLayout mario_left_hand_cap_armature[];
extern const GeoLayout mario_left_hand_wing_cap_armature[];
extern const GeoLayout mario_geo_opt_1[];
extern const GeoLayout mario_geo_opt_2[];
extern const GeoLayout mario_geo_opt_3[];
extern const GeoLayout mario_geo_opt_4[];
extern const GeoLayout mario_geo_opt_5[];
extern const GeoLayout mario_geo_opt_6[];
extern const GeoLayout mario_geo_opt_7[];
extern const GeoLayout mario_geo_opt_1_1[];
extern const GeoLayout mario_geo_opt_2_1[];
extern const GeoLayout mario_geo_opt_3_1[];
extern const GeoLayout mario_geo_opt_4_1[];
extern const GeoLayout mario_geo_opt_5_1[];
extern const GeoLayout mario_geo_opt_6_1[];
extern const GeoLayout mario_geo_opt_7_1[];
extern const GeoLayout mario_geo_opt_1_2_opt_1_opt_1[];
extern const GeoLayout mario_geo_opt_1_2_opt_1_opt_2[];
extern const GeoLayout mario_geo_opt_1_2_opt_1_opt_3[];
extern const GeoLayout mario_geo_opt_1_2_opt_1_opt_4[];
extern const GeoLayout mario_geo_opt_1_2_opt_1_opt_5[];
extern const GeoLayout mario_geo_opt_1_2_opt_1_opt_6[];
extern const GeoLayout mario_geo_opt_1_2_opt_1_opt_7[];
extern const GeoLayout mario_armature_002_switch_option_002_opt_1[];
extern const GeoLayout mario_geo_opt_1_1_opt_1[];
extern const GeoLayout mario_geo_opt_2_1_opt_1[];
extern const GeoLayout mario_geo_opt_3_1_opt_1[];
extern const GeoLayout mario_geo_opt_4_1_opt_1[];
extern const GeoLayout mario_geo_opt_5_1_opt_1[];
extern const GeoLayout mario_geo_opt_6_1_opt_1[];
extern const GeoLayout mario_geo_opt_7_1_opt_1[];
extern const GeoLayout mario_right_hand_open_armature_opt_1[];
extern const GeoLayout mario_left_hand_open_armature_opt_1[];
extern const GeoLayout mario_left_hand_peace_armature_opt_1[];
extern const GeoLayout mario_left_hand_cap_armature_opt_1[];
extern const GeoLayout mario_left_hand_wing_cap_armature_opt_1[];
extern const GeoLayout mario_geo_opt_1_2[];
extern const GeoLayout mario_geo_opt_2_2_opt_2_opt_1[];
extern const GeoLayout mario_geo_opt_2_2_opt_2_opt_2[];
extern const GeoLayout mario_geo_opt_2_2_opt_2_opt_3[];
extern const GeoLayout mario_geo_opt_2_2_opt_2_opt_4[];
extern const GeoLayout mario_geo_opt_2_2_opt_2_opt_5[];
extern const GeoLayout mario_geo_opt_2_2_opt_2_opt_6[];
extern const GeoLayout mario_geo_opt_2_2_opt_2_opt_7[];
extern const GeoLayout mario_armature_002_switch_option_002_opt_2[];
extern const GeoLayout mario_geo_opt_1_1_opt_2[];
extern const GeoLayout mario_geo_opt_2_1_opt_2[];
extern const GeoLayout mario_geo_opt_3_1_opt_2[];
extern const GeoLayout mario_geo_opt_4_1_opt_2[];
extern const GeoLayout mario_geo_opt_5_1_opt_2[];
extern const GeoLayout mario_geo_opt_6_1_opt_2[];
extern const GeoLayout mario_geo_opt_7_1_opt_2[];
extern const GeoLayout mario_right_hand_open_armature_opt_2[];
extern const GeoLayout mario_left_hand_open_armature_opt_2[];
extern const GeoLayout mario_left_hand_peace_armature_opt_2[];
extern const GeoLayout mario_left_hand_cap_armature_opt_2[];
extern const GeoLayout mario_left_hand_wing_cap_armature_opt_2[];
extern const GeoLayout mario_geo_opt_2_2[];
extern const GeoLayout mario_geo_opt_3_2_opt_3_opt_1[];
extern const GeoLayout mario_geo_opt_3_2_opt_3_opt_2[];
extern const GeoLayout mario_geo_opt_3_2_opt_3_opt_3[];
extern const GeoLayout mario_geo_opt_3_2_opt_3_opt_4[];
extern const GeoLayout mario_geo_opt_3_2_opt_3_opt_5[];
extern const GeoLayout mario_geo_opt_3_2_opt_3_opt_6[];
extern const GeoLayout mario_geo_opt_3_2_opt_3_opt_7[];
extern const GeoLayout mario_armature_002_switch_option_002_opt_3[];
extern const GeoLayout mario_geo_opt_1_1_opt_3[];
extern const GeoLayout mario_geo_opt_2_1_opt_3[];
extern const GeoLayout mario_geo_opt_3_1_opt_3[];
extern const GeoLayout mario_geo_opt_4_1_opt_3[];
extern const GeoLayout mario_geo_opt_5_1_opt_3[];
extern const GeoLayout mario_geo_opt_6_1_opt_3[];
extern const GeoLayout mario_geo_opt_7_1_opt_3[];
extern const GeoLayout mario_right_hand_open_armature_opt_3[];
extern const GeoLayout mario_left_hand_open_armature_opt_3[];
extern const GeoLayout mario_left_hand_peace_armature_opt_3[];
extern const GeoLayout mario_left_hand_cap_armature_opt_3[];
extern const GeoLayout mario_left_hand_wing_cap_armature_opt_3[];
extern const GeoLayout mario_geo_opt_3_2[];
extern const GeoLayout mario_geo[];
extern u8 mario_mario_button_ci8[];
extern u8 mario_mario_button_pal_rgba16[];
extern u8 mario_SM64_Luigi_Hat_ci8[];
extern u8 mario_SM64_Luigi_Hat_pal_rgba16[];
extern u8 mario_texture__1__ci8[];
extern u8 mario_texture__1__pal_rgba16[];
extern u8 mario_SM64_Luigi_Stache_ia16[];
extern u8 mario_SM64_Luigi_Hair_ci8[];
extern u8 mario_SM64_Luigi_Hair_pal_rgba16[];
extern u8 mario_texture__1__ci8_copy[];
extern u8 mario_texture__1__pal_rgba16_copy[];
extern u8 mario_SM64_Luigi_Hair_ci8_copy[];
extern u8 mario_SM64_Luigi_Hair_pal_rgba16_copy[];
extern u8 mario_SM64_Luigi_Stache_ia16_copy[];
extern u8 mario_wing_2_ia8[];
extern u8 mario_wing1_ia8[];
extern u8 mario_mario_face_2_ci8[];
extern u8 mario_mario_face_2_pal_rgba16[];
extern u8 mario_mario_face_3_ci8[];
extern u8 mario_mario_face_3_pal_rgba16[];
extern u8 mario_mario_face_4_ia8[];
extern u8 mario_mario_metal_rgba16_tint_ci8[];
extern u8 mario_mario_metal_rgba16_tint_pal_rgba16[];
extern Vtx mario_000_offset_mesh_layer_1_vtx_0[53];
extern Gfx mario_000_offset_mesh_layer_1_tri_0[];
extern Vtx mario_000_offset_001_mesh_layer_1_vtx_0[91];
extern Gfx mario_000_offset_001_mesh_layer_1_tri_0[];
extern Vtx mario_000_offset_001_mesh_layer_1_vtx_1[27];
extern Gfx mario_000_offset_001_mesh_layer_1_tri_1[];
extern Vtx mario_000_displaylist_mesh_layer_1_vtx_0[11];
extern Gfx mario_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx mario_000_displaylist_mesh_layer_1_vtx_1[73];
extern Gfx mario_000_displaylist_mesh_layer_1_tri_1[];
extern Vtx mario_000_displaylist_mesh_layer_1_vtx_2[40];
extern Gfx mario_000_displaylist_mesh_layer_1_tri_2[];
extern Vtx mario_000_displaylist_mesh_layer_1_vtx_3[27];
extern Gfx mario_000_displaylist_mesh_layer_1_tri_3[];
extern Vtx mario_000_displaylist_mesh_layer_1_vtx_4[12];
extern Gfx mario_000_displaylist_mesh_layer_1_tri_4[];
extern Vtx mario_002_switch_option_head__no_cap__mesh_layer_1_vtx_0[127];
extern Gfx mario_002_switch_option_head__no_cap__mesh_layer_1_tri_0[];
extern Vtx mario_002_switch_option_head__no_cap__mesh_layer_1_vtx_1[76];
extern Gfx mario_002_switch_option_head__no_cap__mesh_layer_1_tri_1[];
extern Vtx mario_002_switch_option_head__no_cap__mesh_layer_1_vtx_2[16];
extern Gfx mario_002_switch_option_head__no_cap__mesh_layer_1_tri_2[];
extern Vtx mario_002_switch_option_head__no_cap__mesh_layer_1_vtx_3[29];
extern Gfx mario_002_switch_option_head__no_cap__mesh_layer_1_tri_3[];
extern Vtx mario_000_displaylist_001_mesh_layer_4_vtx_0[5];
extern Gfx mario_000_displaylist_001_mesh_layer_4_tri_0[];
extern Vtx mario_000_displaylist_001_mesh_layer_4_vtx_1[4];
extern Gfx mario_000_displaylist_001_mesh_layer_4_tri_1[];
extern Vtx mario_000_displaylist_002_mesh_layer_4_vtx_0[4];
extern Gfx mario_000_displaylist_002_mesh_layer_4_tri_0[];
extern Vtx mario_000_displaylist_002_mesh_layer_4_vtx_1[4];
extern Gfx mario_000_displaylist_002_mesh_layer_4_tri_1[];
extern Vtx mario_000_offset_003_mesh_layer_1_vtx_0[27];
extern Gfx mario_000_offset_003_mesh_layer_1_tri_0[];
extern Vtx mario_000_offset_004_mesh_layer_1_vtx_0[25];
extern Gfx mario_000_offset_004_mesh_layer_1_tri_0[];
extern Vtx mario_000_displaylist_003_mesh_layer_1_vtx_0[30];
extern Gfx mario_000_displaylist_003_mesh_layer_1_tri_0[];
extern Vtx mario_002_switch_option_right_hand_open_mesh_layer_1_vtx_0[42];
extern Gfx mario_002_switch_option_right_hand_open_mesh_layer_1_tri_0[];
extern Vtx mario_000_offset_006_mesh_layer_1_vtx_0[25];
extern Gfx mario_000_offset_006_mesh_layer_1_tri_0[];
extern Vtx mario_000_offset_007_mesh_layer_1_vtx_0[22];
extern Gfx mario_000_offset_007_mesh_layer_1_tri_0[];
extern Vtx mario_000_displaylist_004_mesh_layer_1_vtx_0[30];
extern Gfx mario_000_displaylist_004_mesh_layer_1_tri_0[];
extern Vtx mario_002_switch_option_left_hand_open_mesh_layer_1_vtx_0[42];
extern Gfx mario_002_switch_option_left_hand_open_mesh_layer_1_tri_0[];
extern Vtx mario_004_switch_option_left_hand_peace_mesh_layer_1_vtx_0[69];
extern Gfx mario_004_switch_option_left_hand_peace_mesh_layer_1_tri_0[];
extern Vtx mario_005_switch_option_left_hand_cap_mesh_layer_1_vtx_0[37];
extern Gfx mario_005_switch_option_left_hand_cap_mesh_layer_1_tri_0[];
extern Vtx mario_005_switch_option_left_hand_cap_mesh_layer_1_vtx_1[10];
extern Gfx mario_005_switch_option_left_hand_cap_mesh_layer_1_tri_1[];
extern Vtx mario_005_switch_option_left_hand_cap_mesh_layer_1_vtx_2[25];
extern Gfx mario_005_switch_option_left_hand_cap_mesh_layer_1_tri_2[];
extern Vtx mario_006_switch_option_left_hand_wing_cap_mesh_layer_1_vtx_0[37];
extern Gfx mario_006_switch_option_left_hand_wing_cap_mesh_layer_1_tri_0[];
extern Vtx mario_006_switch_option_left_hand_wing_cap_mesh_layer_1_vtx_1[10];
extern Gfx mario_006_switch_option_left_hand_wing_cap_mesh_layer_1_tri_1[];
extern Vtx mario_006_switch_option_left_hand_wing_cap_mesh_layer_1_vtx_2[25];
extern Gfx mario_006_switch_option_left_hand_wing_cap_mesh_layer_1_tri_2[];
extern Vtx mario_006_switch_option_left_hand_wing_cap_wings_mesh_layer_4_vtx_0[8];
extern Gfx mario_006_switch_option_left_hand_wing_cap_wings_mesh_layer_4_tri_0[];
extern Vtx mario_006_switch_option_left_hand_wing_cap_wings_mesh_layer_4_vtx_1[8];
extern Gfx mario_006_switch_option_left_hand_wing_cap_wings_mesh_layer_4_tri_1[];
extern Vtx mario_000_offset_009_mesh_layer_1_vtx_0[17];
extern Gfx mario_000_offset_009_mesh_layer_1_tri_0[];
extern Vtx mario_000_offset_010_mesh_layer_1_vtx_0[12];
extern Gfx mario_000_offset_010_mesh_layer_1_tri_0[];
extern Vtx mario_000_offset_011_mesh_layer_1_vtx_0[23];
extern Gfx mario_000_offset_011_mesh_layer_1_tri_0[];
extern Vtx mario_000_offset_012_mesh_layer_1_vtx_0[17];
extern Gfx mario_000_offset_012_mesh_layer_1_tri_0[];
extern Vtx mario_000_offset_013_mesh_layer_1_vtx_0[22];
extern Gfx mario_000_offset_013_mesh_layer_1_tri_0[];
extern Vtx mario_000_displaylist_005_mesh_layer_1_vtx_0[23];
extern Gfx mario_000_displaylist_005_mesh_layer_1_tri_0[];
extern Gfx mat_mario_body_v3[];
extern Gfx mat_revert_mario_body_v3[];
extern Gfx mat_mario_cap_v3[];
extern Gfx mat_revert_mario_cap_v3[];
extern Gfx mat_mario_hair_v3_001[];
extern Gfx mat_revert_mario_hair_v3_001[];
extern Gfx mat_mario_face_0___eye_open_v3_001[];
extern Gfx mat_revert_mario_face_0___eye_open_v3_001[];
extern Gfx mat_mario_mustache_v3_001[];
extern Gfx mat_revert_mario_mustache_v3_001[];
extern Gfx mat_mario_sideburns_v3_001[];
extern Gfx mat_revert_mario_sideburns_v3_001[];
extern Gfx mat_mario_hair_v3_002[];
extern Gfx mat_revert_mario_hair_v3_002[];
extern Gfx mat_mario_face_0___eye_open_v3_002[];
extern Gfx mat_revert_mario_face_0___eye_open_v3_002[];
extern Gfx mat_mario_sideburns_v3_002[];
extern Gfx mat_revert_mario_sideburns_v3_002[];
extern Gfx mat_mario_mustache_v3_002[];
extern Gfx mat_revert_mario_mustache_v3_002[];
extern Gfx mat_mario_wing_2_v3_001[];
extern Gfx mat_revert_mario_wing_2_v3_001[];
extern Gfx mat_mario_wing_1_v3_001[];
extern Gfx mat_revert_mario_wing_1_v3_001[];
extern Gfx mat_mario_gloves_v3_001[];
extern Gfx mat_revert_mario_gloves_v3_001[];
extern Gfx mat_mario_cap_inside[];
extern Gfx mat_revert_mario_cap_inside[];
extern Gfx mat_mario_shoes_v3_001[];
extern Gfx mat_revert_mario_shoes_v3_001[];
extern Gfx mat_mario_face_1___eye_half_v3_001[];
extern Gfx mat_revert_mario_face_1___eye_half_v3_001[];
extern Gfx mat_mario_face_2___eye_closed_v3_001[];
extern Gfx mat_revert_mario_face_2___eye_closed_v3_001[];
extern Gfx mat_mario_face_7___eye_X_v3_001[];
extern Gfx mat_revert_mario_face_7___eye_X_v3_001[];
extern Gfx mat_mario_metal_v3_001[];
extern Gfx mat_revert_mario_metal_v3_001[];
extern Gfx mario_000_offset_mesh_layer_1[];
extern Gfx mario_000_offset_mesh_layer_1_opt_2[];
extern Gfx mario_000_offset_001_mesh_layer_1[];
extern Gfx mario_000_offset_001_mesh_layer_1_opt_2[];
extern Gfx mario_000_displaylist_mesh_layer_1[];
extern Gfx mario_000_displaylist_mesh_layer_1_opt_1[];
extern Gfx mario_000_displaylist_mesh_layer_1_opt_2[];
extern Gfx mario_000_displaylist_mesh_layer_1_opt_7[];
extern Gfx mario_000_displaylist_mesh_layer_1_opt_2_0[];
extern Gfx mario_002_switch_option_head__no_cap__mesh_layer_1[];
extern Gfx mario_002_switch_option_head__no_cap__mesh_layer_1_opt_2[];
extern Gfx mario_000_displaylist_001_mesh_layer_4[];
extern Gfx mario_000_displaylist_002_mesh_layer_4[];
extern Gfx mario_000_offset_003_mesh_layer_1[];
extern Gfx mario_000_offset_003_mesh_layer_1_opt_2[];
extern Gfx mario_000_offset_004_mesh_layer_1[];
extern Gfx mario_000_offset_004_mesh_layer_1_opt_2[];
extern Gfx mario_000_displaylist_003_mesh_layer_1[];
extern Gfx mario_000_displaylist_003_mesh_layer_1_opt_2[];
extern Gfx mario_002_switch_option_right_hand_open_mesh_layer_1[];
extern Gfx mario_002_switch_option_right_hand_open_mesh_layer_1_opt_2[];
extern Gfx mario_000_offset_006_mesh_layer_1[];
extern Gfx mario_000_offset_006_mesh_layer_1_opt_2[];
extern Gfx mario_000_offset_007_mesh_layer_1[];
extern Gfx mario_000_offset_007_mesh_layer_1_opt_2[];
extern Gfx mario_000_displaylist_004_mesh_layer_1[];
extern Gfx mario_000_displaylist_004_mesh_layer_1_opt_2[];
extern Gfx mario_002_switch_option_left_hand_open_mesh_layer_1[];
extern Gfx mario_002_switch_option_left_hand_open_mesh_layer_1_opt_2[];
extern Gfx mario_004_switch_option_left_hand_peace_mesh_layer_1[];
extern Gfx mario_004_switch_option_left_hand_peace_mesh_layer_1_opt_2[];
extern Gfx mario_005_switch_option_left_hand_cap_mesh_layer_1[];
extern Gfx mario_005_switch_option_left_hand_cap_mesh_layer_1_opt_2[];
extern Gfx mario_006_switch_option_left_hand_wing_cap_mesh_layer_1[];
extern Gfx mario_006_switch_option_left_hand_wing_cap_mesh_layer_1_opt_2[];
extern Gfx mario_006_switch_option_left_hand_wing_cap_wings_mesh_layer_4[];
extern Gfx mario_006_switch_option_left_hand_wing_cap_wings_mesh_layer_4_with_layer_4_revert[];
extern Gfx mario_000_offset_009_mesh_layer_1[];
extern Gfx mario_000_offset_009_mesh_layer_1_opt_2[];
extern Gfx mario_000_offset_010_mesh_layer_1[];
extern Gfx mario_000_offset_010_mesh_layer_1_opt_2[];
extern Gfx mario_000_offset_011_mesh_layer_1[];
extern Gfx mario_000_offset_011_mesh_layer_1_opt_2[];
extern Gfx mario_000_offset_012_mesh_layer_1[];
extern Gfx mario_000_offset_012_mesh_layer_1_opt_2[];
extern Gfx mario_000_offset_013_mesh_layer_1[];
extern Gfx mario_000_offset_013_mesh_layer_1_opt_2[];
extern Gfx mario_000_displaylist_005_mesh_layer_1_with_layer_1_revert[];
extern Gfx mario_000_displaylist_005_mesh_layer_1_opt_2_with_layer_1_revert[];
extern Gfx mario_000_displaylist_005_mesh_layer_1_with_layer_5_revert[];
