extern const GeoLayout wf_area_1_geo[];
extern const GeoLayout wf_area_1[];
extern const Collision wf_area_1_collision[];
extern const MacroObject wf_area_1_macro_objs[];
extern Vtx wf_dl_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx wf_dl_Cube_mesh_layer_1_vtx_0[20];
extern Gfx wf_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_mesh_layer_1_vtx_1[134];
extern Gfx wf_dl_Cube_mesh_layer_1_tri_1[];
extern Vtx wf_dl_Plane_mesh_layer_5_vtx_cull[8];
extern Vtx wf_dl_Plane_mesh_layer_5_vtx_0[4];
extern Gfx wf_dl_Plane_mesh_layer_5_tri_0[];
extern Gfx mat_wf_dl_woodSound[];
extern Gfx mat_revert_wf_dl_woodSound[];
extern Gfx mat_wf_dl_stoneSound[];
extern Gfx mat_revert_wf_dl_stoneSound[];
extern Gfx mat_wf_dl_deathplane[];
extern Gfx mat_revert_wf_dl_deathplane[];
extern Gfx wf_dl_Cube_mesh_layer_1[];
extern Gfx wf_dl_Plane_mesh_layer_5[];
